### ISSUE TITLE
CSS is not loaded

### ISSUE THREAD

**Issue by rhukster** [getgrav/grav-theme-striped#1]
Seems CSS is loaded between `<noscript>` tags causing them to not be processed by the browser.

**Comment by hexplor** [comment]
I'm unable to replicate this. More informations needed.

**Comment by indigo423** [comment]
I can confirm this issue, tried installing skeleton and theme via bin/gpm install

**Comment by hexplor** [comment]
hello indigo423,
can you send me your whole grav directory to karol@rockettheme.com or using gitter ? I would love to replicate that issue.

**Comment by mrsarge** [comment]
Just got the issue on a new installation.  Downloaded and extracted "grav-skeleton-striped-site-v1.0.1.zip" from the getgrav.org website.  Installed the grav-plugin-highlight via gpm.  Some CSS are being put inside a `<noscript>` tag.

``` html
<noscript>
  <link href="/grav/user/plugins/highlight/css/monokai_sublime.css" type="text/css" rel="stylesheet" />
  <link href="/grav/user/themes/striped/css/skel.css" type="text/css" rel="stylesheet" />
  <link href="/grav/user/themes/striped/css/style.css" type="text/css" rel="stylesheet" />
  <link href="/grav/user/themes/striped/css/style-desktop.css" type="text/css" rel="stylesheet" />
  <link href="/grav/user/themes/striped/css/style-wide.css" type="text/css" rel="stylesheet" />
</noscript>
```

style.css, style-desktop.css and style-wide.css are still working because they seem to be loaded by a javascript function just above the noscript block:

``` javascript
<script type="text/javascript">
(function($) {
  skel.init({
    reset: 'full',
    breakpoints: {
      global:   { range: '*', href: '/grav/user/themes/striped/css/style.css', containers: '100%', grid: { gutters: 50 }, viewport: { scalable: false } },
      desktop:  { range: '737-', href: '/grav/user/themes/striped/css/style-desktop.css' },
      wide:   { range: '1201-', href: '/grav/user/themes/striped/css/style-wide.css' },
      narrow:   { range: '737-1200', href: '/grav/user/themes/striped/css/style-narrow.css' },
      narrower: { range: '737-1000', href: '/grav/user/themes/striped/css/style-narrower.css' },
      mobile:   { range: '-736', href: '/grav/user/themes/striped/css/style-mobile.css', containers: '100%!', grid: { collapse: true } }
},
```

**Comment by hexplor** [comment]
New version of Striped was released recently without these <noscript> tags. I'm already updating striped grav theme to reflect these changes. Stay tuned for updates.
